name: Auth Code Quality Checks

on:
  pull_request:
    paths:
      - 'auth_service/**'
    branches:
      - master
      - dev
  push:
    paths:
      - 'auth_service/**'
    branches:
      - master
      - dev

jobs:
  linting_and_formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.virtualenvs
          key: ${{ runner.os }}-poetry-auth_service-${{ hashFiles('auth_service/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-auth_service-

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies with Poetry
        run: |
          cd auth_service
          poetry install --no-interaction --no-root --with dev

      - name: Run black (formatting)
        run: |
          cd auth_service
          poetry run black --check .

      - name: Run ruff (linting)
        run: |
          cd auth_service
          poetry run ruff check .

  type_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.virtualenvs
          key: ${{ runner.os }}-poetry-auth_service-${{ hashFiles('auth_service/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-auth_service-

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies with Poetry
        run: |
          cd auth_service
          poetry install --no-interaction --no-root --with dev

      - name: Run mypy
        run: |
          cd auth_service
          poetry run mypy . --ignore-missing-imports
